// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD4qFsdfwn8MOr_65lnqFaKENibTnVbbo',
    appId: '1:316001095342:web:6299e85f83ea4fe056673f',
    messagingSenderId: '316001095342',
    projectId: 'khanet-elgamal',
    authDomain: 'khanet-elgamal.firebaseapp.com',
    storageBucket: 'khanet-elgamal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUu04IpdIBo2w1XE-T8UC9lhkeM82tBD8',
    appId: '1:316001095342:android:481f68dfb200166256673f',
    messagingSenderId: '316001095342',
    projectId: 'khanet-elgamal',
    storageBucket: 'khanet-elgamal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIXOr0sb5UijQloZ4q6cSxQ5DPvA8kB8k',
    appId: '1:316001095342:ios:7ad6982e4ce34a9a56673f',
    messagingSenderId: '316001095342',
    projectId: 'khanet-elgamal',
    storageBucket: 'khanet-elgamal.appspot.com',
    iosClientId: '316001095342-r95la8o8a2fpc6nu6puoofeisldij0gv.apps.googleusercontent.com',
    iosBundleId: 'com.eibtek.khanetgamal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIXOr0sb5UijQloZ4q6cSxQ5DPvA8kB8k',
    appId: '1:316001095342:ios:7ad6982e4ce34a9a56673f',
    messagingSenderId: '316001095342',
    projectId: 'khanet-elgamal',
    storageBucket: 'khanet-elgamal.appspot.com',
    iosClientId: '316001095342-r95la8o8a2fpc6nu6puoofeisldij0gv.apps.googleusercontent.com',
    iosBundleId: 'com.eibtek.khanetgamal',
  );
}
